DELETE http://localhost:3003/api/blogs/6167ea838d3b19067dd393b4
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InRlc3RlciIsImlkIjoiNjE2NmY2YWVkMTRlODAxODQ0MzRmNmMyIiwiaWF0IjoxNjM0MjAwMTc5LCJleHAiOjE2MzQyMDM3Nzl9.P8YTPwSbNolwuY9j5wr002xCNG6fOSeKNBe-wFsRKZA